title: Kaushik Pradhan
position: BS-MS Dual Degree Student
affiliation: Department of Earth Sciences, IISER Kolkata
email: kkp16ms169@iiserkol.ac.in
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=7wTfouwAAAAJ&hl=en&oi=ao
github_link: https://github.com/pradhankaushik
linkedin: https://www.linkedin.com/in/kaushik-pradhan/
avatar: https://github.com/pradhankaushik/pradhankaushik.github.io/assets/img/kaushik_profile.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
